### model
model_name_or_path: Qwen/Qwen2.5-3B-Instruct
trust_remote_code: true
flash_attn: auto

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.05

### dataset
dataset_dir: /root/autodl-tmp/qwen-med-align-auto/data/llamafactory
dataset: stage1_med_sft_train,stage1_redflag_sft
template: qwen
cutoff_len: 2048
max_samples: 30000
overwrite_cache: true
preprocessing_num_workers: 4

### output
output_dir: /root/autodl-tmp/qwen-med-runs/general-med-lora
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 2.0e-4
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.05
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 100
